<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper container">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page row">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col3-layout row">
            <div class="main col-xs-12">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-wrapper col-xs-9">
                    <div class="col-main col-xs-9 col-sm-push-3">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                    <div class="col-left sidebar col-xs-3 col-sm-pull-9"><?php echo $this->getChildHtml('left') ?></div>
                </div>
                <div class="col-right sidebar col-xs-3"><?php echo $this->getChildHtml('right') ?></div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
