<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>
    <div class="nav-wrap visible-xs">
        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#panelCategory">
                        Category
                    </a></div>
            </div>
            <div class="panel-collapse collapse" id="panelCategory">
                <div id="nav-container" class="panel-body">
                    <ul id="nav-xs">
                        <?php echo $_menu ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>