<div class="block block-tags hidden-xs well well-sm">
    <div class="block-title">
        <strong><span><?php echo $this->__('Popular Tags'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="tags-list">
            <?php foreach ($this->getTags() as $_tag): ?>
                <li><a href="<?php echo $_tag->getTaggedProductsUrl() ?>" style="font-size:<?php echo $_tag->getRatio()*70+75 ?>%;"><?php echo $this->escapeHtml($_tag->getName()) ?></a></li>
            <?php endforeach; ?>
        </ul>
        <div class="actions">
            <a href="<?php echo $this->getUrl('tag/list') ?>"><?php echo $this->__('View All Tags') ?></a>
        </div>
    </div>
</div>
